name: OZIP Decrypter

on:
  
  push: # push触发
    branches: [ master ]
  workflow_dispatch: # 手动触发


env:
  FIRMWARE_LINK: https://bj29.cn-beijing.data.alicloudccp.com/mK8IDjXb%2F1681696%2F605a9d72273f619541504a94b6e8816888e0a51e%2F605a9d7248d97ec13233441396ad4bc82ad9f13c?di=bj29&dr=1645337&f=6108dc2080250c3640bb4d88a535964e376e42e9&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27RMX2111_11_OTA_0330_all_7ol48BnFhhDl_bb94e9ce0.ozip&u=a774381df53a4865b1a53819d44fd3a1&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1637438255&x-oss-signature=N4FPiMW8Z8kI%2F5sGo1ztq0WNgHn98j0C9qyCzI0PJOE%3D&x-oss-signature-version=OSS2 
  FIRMWARE_NAME: RMX2111_11_OTA_0330_all_7ol48BnFhhDl_bb94e9ce0.ozip
  FIRMWARE_ZIP_NAME: RMX2111_11_OTA_0330_all_7ol48BnFhhDl_bb94e9ce0.zip

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2 expect -y
            aria2c $FIRMWARE_LINK
            
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python3-pip
             sudo -H pip3 install --upgrade pip
             sudo -H pip3 install setuptools wheel pycryptodome
             wget https://github.com/bkerler/oppo_ozip_decrypt/raw/master/ozipdecrypt.py
             sudo python3 ozipdecrypt.py $FIRMWARE_NAME
             
       - name: Upload Zip Now
         run: |
             curl -k -F "file=@$FIRMWARE_ZIP_NAME" -F "token=jfffjwj7od6wlkmzgiw8" -F "model=0"  -X POST "https://connect.tmp.link/api_v2/cli_uploader"
             curl --insecure --upload-file $FIRMWARE_ZIP_NAME https://transfer.sh/rmx2111.zip
             curl https://bashupload.com/ -T $FIRMWARE_ZIP_NAME
