name: OZIP Decrypter

on:
  
  push: # push触发
    branches: [ master ]
  workflow_dispatch: # 手动触发


env:
  FIRMWARE_LINK: https://download.c.realme.com/osupdate/RMX2111_11_OTA_0300_all_bJRowbrIvv35.ozip
  FIRMWARE_NAME: RMX2111_11_OTA_0300_all_bJRowbrIvv35.ozip
  FIRMWARE_ZIP_NAME: RMX2111_11_OTA_0300_all_bJRowbrIvv35
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2 expect -y
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python3-pip
             sudo -H pip3 install --upgrade pip
             sudo -H pip3 install setuptools wheel pycryptodome
             wget https://github.com/bkerler/oppo_ozip_decrypt/raw/master/ozipdecrypt.py
             sudo python3 ozipdecrypt.py $FIRMWARE_NAME
             curl --upload-file $FIRMWARE_ZIP_NAME.zip https://transfer.sh/firmware20210806.zip
