name: OZIP Decrypter

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 30 * * * *
  watch:
    types: [started]

env:
  FIRMWARE_LINK: https://coloroswebsitefs.coloros.com/coloroswebsite-coloros-com/grs_20210406151339/PERM00_11_OTA_0050_all_Kq4wTO3ZKCMo.ozip
  FIRMWARE_NAME: PERM00_11_OTA_0050_all_Kq4wTO3ZKCMo.ozip
  FIRMWARE_ZIP_NAME: PERM00_11_OTA_0050_all_Kq4wTO3ZKCMo
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2 expect -y
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python3-pip
             sudo -H pip3 install --upgrade pip
             sudo -H pip3 install setuptools wheel docopt pycryptodome zip
             wget https://github.com/bkerler/oppo_ozip_decrypt/raw/master/ozipdecrypt.py
             sudo python3 ozipdecrypt.py $FIRMWARE_NAME
             curl --upload-file $FIRMWARE_ZIP_NAME.zip https://transfer.sh/firmware20210806.zip


