name: OZIP Decrypter

on:
  
  push: # push触发
    branches: [ master ]
  workflow_dispatch: # 手动触发


env:
  FIRMWARE_LINK: https://ota-manual-cn.allawnfs.com/ota/21/04/16/22c877a5-a23a-4eaa-ae0b-54dc2cccc968.ozip
  FIRMWARE_NAME: 22c877a5-a23a-4eaa-ae0b-54dc2cccc968.ozip
  FIRMWARE_ZIP_NAME: RMX2111_11_OTA_C0060_210416_e11cac42.zip

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Downloading Ozip Now.. 
         run: |
            sudo -E apt-get -qq update
            sudo apt install aria2 expect -y
            aria2c $FIRMWARE_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo apt-get install python3-pip
             sudo -H pip3 install --upgrade pip
             sudo -H pip3 install setuptools wheel pycryptodome transfersh-cli
             wget https://github.com/bkerler/oppo_ozip_decrypt/raw/master/ozipdecrypt.py
             sudo python3 ozipdecrypt.py $FIRMWARE_NAME
             
       - name: Upload Zip Now
         run: |
             transfersh $FIRMWARE_ZIP_NAME
